%-----------------------------------------------------------------------
% Job saved on 11-Aug-2022 00:49:39 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.stats.fmri_spec.dir = {'glm'};
matlabbatch{1}.spm.stats.fmri_spec.timing.units = 'secs';
matlabbatch{1}.spm.stats.fmri_spec.timing.RT = 2;
matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t = 31;
matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t0 = 16;
%%
matlabbatch{1}.spm.stats.fmri_spec.sess.scans = {
                                                 'nifti/rfmri.nii,1'
                                                 'nifti/rfmri.nii,2'
                                                 'nifti/rfmri.nii,3'
                                                 'nifti/rfmri.nii,4'
                                                 'nifti/rfmri.nii,5'
                                                 'nifti/rfmri.nii,6'
                                                 'nifti/rfmri.nii,7'
                                                 'nifti/rfmri.nii,8'
                                                 'nifti/rfmri.nii,9'
                                                 'nifti/rfmri.nii,10'
                                                 'nifti/rfmri.nii,11'
                                                 'nifti/rfmri.nii,12'
                                                 'nifti/rfmri.nii,13'
                                                 'nifti/rfmri.nii,14'
                                                 'nifti/rfmri.nii,15'
                                                 'nifti/rfmri.nii,16'
                                                 'nifti/rfmri.nii,17'
                                                 'nifti/rfmri.nii,18'
                                                 'nifti/rfmri.nii,19'
                                                 'nifti/rfmri.nii,20'
                                                 'nifti/rfmri.nii,21'
                                                 'nifti/rfmri.nii,22'
                                                 'nifti/rfmri.nii,23'
                                                 'nifti/rfmri.nii,24'
                                                 'nifti/rfmri.nii,25'
                                                 'nifti/rfmri.nii,26'
                                                 'nifti/rfmri.nii,27'
                                                 'nifti/rfmri.nii,28'
                                                 'nifti/rfmri.nii,29'
                                                 'nifti/rfmri.nii,30'
                                                 'nifti/rfmri.nii,31'
                                                 'nifti/rfmri.nii,32'
                                                 'nifti/rfmri.nii,33'
                                                 'nifti/rfmri.nii,34'
                                                 'nifti/rfmri.nii,35'
                                                 'nifti/rfmri.nii,36'
                                                 'nifti/rfmri.nii,37'
                                                 'nifti/rfmri.nii,38'
                                                 'nifti/rfmri.nii,39'
                                                 'nifti/rfmri.nii,40'
                                                 'nifti/rfmri.nii,41'
                                                 'nifti/rfmri.nii,42'
                                                 'nifti/rfmri.nii,43'
                                                 'nifti/rfmri.nii,44'
                                                 'nifti/rfmri.nii,45'
                                                 'nifti/rfmri.nii,46'
                                                 'nifti/rfmri.nii,47'
                                                 'nifti/rfmri.nii,48'
                                                 'nifti/rfmri.nii,49'
                                                 'nifti/rfmri.nii,50'
                                                 'nifti/rfmri.nii,51'
                                                 'nifti/rfmri.nii,52'
                                                 'nifti/rfmri.nii,53'
                                                 'nifti/rfmri.nii,54'
                                                 'nifti/rfmri.nii,55'
                                                 'nifti/rfmri.nii,56'
                                                 'nifti/rfmri.nii,57'
                                                 'nifti/rfmri.nii,58'
                                                 'nifti/rfmri.nii,59'
                                                 'nifti/rfmri.nii,60'
                                                 'nifti/rfmri.nii,61'
                                                 'nifti/rfmri.nii,62'
                                                 'nifti/rfmri.nii,63'
                                                 'nifti/rfmri.nii,64'
                                                 'nifti/rfmri.nii,65'
                                                 'nifti/rfmri.nii,66'
                                                 'nifti/rfmri.nii,67'
                                                 'nifti/rfmri.nii,68'
                                                 'nifti/rfmri.nii,69'
                                                 'nifti/rfmri.nii,70'
                                                 'nifti/rfmri.nii,71'
                                                 'nifti/rfmri.nii,72'
                                                 'nifti/rfmri.nii,73'
                                                 'nifti/rfmri.nii,74'
                                                 'nifti/rfmri.nii,75'
                                                 'nifti/rfmri.nii,76'
                                                 'nifti/rfmri.nii,77'
                                                 'nifti/rfmri.nii,78'
                                                 'nifti/rfmri.nii,79'
                                                 'nifti/rfmri.nii,80'
                                                 'nifti/rfmri.nii,81'
                                                 'nifti/rfmri.nii,82'
                                                 'nifti/rfmri.nii,83'
                                                 'nifti/rfmri.nii,84'
                                                 'nifti/rfmri.nii,85'
                                                 'nifti/rfmri.nii,86'
                                                 'nifti/rfmri.nii,87'
                                                 'nifti/rfmri.nii,88'
                                                 'nifti/rfmri.nii,89'
                                                 'nifti/rfmri.nii,90'
                                                 'nifti/rfmri.nii,91'
                                                 'nifti/rfmri.nii,92'
                                                 'nifti/rfmri.nii,93'
                                                 'nifti/rfmri.nii,94'
                                                 'nifti/rfmri.nii,95'
                                                 'nifti/rfmri.nii,96'
                                                 'nifti/rfmri.nii,97'
                                                 'nifti/rfmri.nii,98'
                                                 'nifti/rfmri.nii,99'
                                                 'nifti/rfmri.nii,100'
                                                 'nifti/rfmri.nii,101'
                                                 'nifti/rfmri.nii,102'
                                                 'nifti/rfmri.nii,103'
                                                 'nifti/rfmri.nii,104'
                                                 'nifti/rfmri.nii,105'
                                                 'nifti/rfmri.nii,106'
                                                 'nifti/rfmri.nii,107'
                                                 'nifti/rfmri.nii,108'
                                                 'nifti/rfmri.nii,109'
                                                 'nifti/rfmri.nii,110'
                                                 'nifti/rfmri.nii,111'
                                                 'nifti/rfmri.nii,112'
                                                 'nifti/rfmri.nii,113'
                                                 'nifti/rfmri.nii,114'
                                                 'nifti/rfmri.nii,115'
                                                 'nifti/rfmri.nii,116'
                                                 'nifti/rfmri.nii,117'
                                                 'nifti/rfmri.nii,118'
                                                 'nifti/rfmri.nii,119'
                                                 'nifti/rfmri.nii,120'
                                                 'nifti/rfmri.nii,121'
                                                 'nifti/rfmri.nii,122'
                                                 'nifti/rfmri.nii,123'
                                                 'nifti/rfmri.nii,124'
                                                 'nifti/rfmri.nii,125'
                                                 'nifti/rfmri.nii,126'
                                                 'nifti/rfmri.nii,127'
                                                 'nifti/rfmri.nii,128'
                                                 'nifti/rfmri.nii,129'
                                                 'nifti/rfmri.nii,130'
                                                 'nifti/rfmri.nii,131'
                                                 'nifti/rfmri.nii,132'
                                                 'nifti/rfmri.nii,133'
                                                 'nifti/rfmri.nii,134'
                                                 'nifti/rfmri.nii,135'
                                                 'nifti/rfmri.nii,136'
                                                 'nifti/rfmri.nii,137'
                                                 'nifti/rfmri.nii,138'
                                                 'nifti/rfmri.nii,139'
                                                 'nifti/rfmri.nii,140'
                                                 'nifti/rfmri.nii,141'
                                                 'nifti/rfmri.nii,142'
                                                 'nifti/rfmri.nii,143'
                                                 'nifti/rfmri.nii,144'
                                                 'nifti/rfmri.nii,145'
                                                 'nifti/rfmri.nii,146'
                                                 'nifti/rfmri.nii,147'
                                                 'nifti/rfmri.nii,148'
                                                 'nifti/rfmri.nii,149'
                                                 'nifti/rfmri.nii,150'
                                                 'nifti/rfmri.nii,151'
                                                 'nifti/rfmri.nii,152'
                                                 'nifti/rfmri.nii,153'
                                                 'nifti/rfmri.nii,154'
                                                 'nifti/rfmri.nii,155'
                                                 'nifti/rfmri.nii,156'
                                                 'nifti/rfmri.nii,157'
                                                 'nifti/rfmri.nii,158'
                                                 'nifti/rfmri.nii,159'
                                                 'nifti/rfmri.nii,160'
                                                 'nifti/rfmri.nii,161'
                                                 'nifti/rfmri.nii,162'
                                                 'nifti/rfmri.nii,163'
                                                 'nifti/rfmri.nii,164'
                                                 'nifti/rfmri.nii,165'
                                                 'nifti/rfmri.nii,166'
                                                 'nifti/rfmri.nii,167'
                                                 'nifti/rfmri.nii,168'
                                                 'nifti/rfmri.nii,169'
                                                 'nifti/rfmri.nii,170'
                                                 'nifti/rfmri.nii,171'
                                                 'nifti/rfmri.nii,172'
                                                 'nifti/rfmri.nii,173'
                                                 'nifti/rfmri.nii,174'
                                                 'nifti/rfmri.nii,175'
                                                 'nifti/rfmri.nii,176'
                                                 'nifti/rfmri.nii,177'
                                                 'nifti/rfmri.nii,178'
                                                 'nifti/rfmri.nii,179'
                                                 'nifti/rfmri.nii,180'
                                                 'nifti/rfmri.nii,181'
                                                 'nifti/rfmri.nii,182'
                                                 'nifti/rfmri.nii,183'
                                                 'nifti/rfmri.nii,184'
                                                 'nifti/rfmri.nii,185'
                                                 'nifti/rfmri.nii,186'
                                                 'nifti/rfmri.nii,187'
                                                 'nifti/rfmri.nii,188'
                                                 'nifti/rfmri.nii,189'
                                                 'nifti/rfmri.nii,190'
                                                 'nifti/rfmri.nii,191'
                                                 'nifti/rfmri.nii,192'
                                                 'nifti/rfmri.nii,193'
                                                 'nifti/rfmri.nii,194'
                                                 'nifti/rfmri.nii,195'
                                                 'nifti/rfmri.nii,196'
                                                 'nifti/rfmri.nii,197'
                                                 'nifti/rfmri.nii,198'
                                                 'nifti/rfmri.nii,199'
                                                 'nifti/rfmri.nii,200'
                                                 'nifti/rfmri.nii,201'
                                                 'nifti/rfmri.nii,202'
                                                 'nifti/rfmri.nii,203'
                                                 'nifti/rfmri.nii,204'
                                                 'nifti/rfmri.nii,205'
                                                 'nifti/rfmri.nii,206'
                                                 'nifti/rfmri.nii,207'
                                                 'nifti/rfmri.nii,208'
                                                 'nifti/rfmri.nii,209'
                                                 'nifti/rfmri.nii,210'
                                                 };
%%
matlabbatch{1}.spm.stats.fmri_spec.sess.cond = struct('name', {}, 'onset', {}, 'duration', {}, 'tmod', {}, 'pmod', {}, 'orth', {});
matlabbatch{1}.spm.stats.fmri_spec.sess.multi = {''};
matlabbatch{1}.spm.stats.fmri_spec.sess.regress = struct('name', {}, 'val', {});
matlabbatch{1}.spm.stats.fmri_spec.sess.multi_reg = {'physio_out/multiple_regressors.txt'};
matlabbatch{1}.spm.stats.fmri_spec.sess.hpf = 128;
matlabbatch{1}.spm.stats.fmri_spec.fact = struct('name', {}, 'levels', {});
matlabbatch{1}.spm.stats.fmri_spec.bases.hrf.derivs = [0 0];
matlabbatch{1}.spm.stats.fmri_spec.volt = 1;
matlabbatch{1}.spm.stats.fmri_spec.global = 'None';
matlabbatch{1}.spm.stats.fmri_spec.mthresh = 0.8;
matlabbatch{1}.spm.stats.fmri_spec.mask = {''};
matlabbatch{1}.spm.stats.fmri_spec.cvi = 'AR(1)';
matlabbatch{2}.spm.stats.fmri_est.spmmat(1) = cfg_dep('fMRI model specification: SPM.mat File', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{2}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;
