%-----------------------------------------------------------------------
% Job saved on 20-Nov-2022 12:56:47 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
%%
matlabbatch{1}.spm.spatial.realign.estwrite.data = {
                                                    {
                                                    'nifti/fmri.nii,1'
                                                    'nifti/fmri.nii,2'
                                                    'nifti/fmri.nii,3'
                                                    'nifti/fmri.nii,4'
                                                    'nifti/fmri.nii,5'
                                                    'nifti/fmri.nii,6'
                                                    'nifti/fmri.nii,7'
                                                    'nifti/fmri.nii,8'
                                                    'nifti/fmri.nii,9'
                                                    'nifti/fmri.nii,10'
                                                    'nifti/fmri.nii,11'
                                                    'nifti/fmri.nii,12'
                                                    'nifti/fmri.nii,13'
                                                    'nifti/fmri.nii,14'
                                                    'nifti/fmri.nii,15'
                                                    'nifti/fmri.nii,16'
                                                    'nifti/fmri.nii,17'
                                                    'nifti/fmri.nii,18'
                                                    'nifti/fmri.nii,19'
                                                    'nifti/fmri.nii,20'
                                                    'nifti/fmri.nii,21'
                                                    'nifti/fmri.nii,22'
                                                    'nifti/fmri.nii,23'
                                                    'nifti/fmri.nii,24'
                                                    'nifti/fmri.nii,25'
                                                    'nifti/fmri.nii,26'
                                                    'nifti/fmri.nii,27'
                                                    'nifti/fmri.nii,28'
                                                    'nifti/fmri.nii,29'
                                                    'nifti/fmri.nii,30'
                                                    'nifti/fmri.nii,31'
                                                    'nifti/fmri.nii,32'
                                                    'nifti/fmri.nii,33'
                                                    'nifti/fmri.nii,34'
                                                    'nifti/fmri.nii,35'
                                                    'nifti/fmri.nii,36'
                                                    'nifti/fmri.nii,37'
                                                    'nifti/fmri.nii,38'
                                                    'nifti/fmri.nii,39'
                                                    'nifti/fmri.nii,40'
                                                    'nifti/fmri.nii,41'
                                                    'nifti/fmri.nii,42'
                                                    'nifti/fmri.nii,43'
                                                    'nifti/fmri.nii,44'
                                                    'nifti/fmri.nii,45'
                                                    'nifti/fmri.nii,46'
                                                    'nifti/fmri.nii,47'
                                                    'nifti/fmri.nii,48'
                                                    'nifti/fmri.nii,49'
                                                    'nifti/fmri.nii,50'
                                                    'nifti/fmri.nii,51'
                                                    'nifti/fmri.nii,52'
                                                    'nifti/fmri.nii,53'
                                                    'nifti/fmri.nii,54'
                                                    'nifti/fmri.nii,55'
                                                    'nifti/fmri.nii,56'
                                                    'nifti/fmri.nii,57'
                                                    'nifti/fmri.nii,58'
                                                    'nifti/fmri.nii,59'
                                                    'nifti/fmri.nii,60'
                                                    'nifti/fmri.nii,61'
                                                    'nifti/fmri.nii,62'
                                                    'nifti/fmri.nii,63'
                                                    'nifti/fmri.nii,64'
                                                    'nifti/fmri.nii,65'
                                                    'nifti/fmri.nii,66'
                                                    'nifti/fmri.nii,67'
                                                    'nifti/fmri.nii,68'
                                                    'nifti/fmri.nii,69'
                                                    'nifti/fmri.nii,70'
                                                    'nifti/fmri.nii,71'
                                                    'nifti/fmri.nii,72'
                                                    'nifti/fmri.nii,73'
                                                    'nifti/fmri.nii,74'
                                                    'nifti/fmri.nii,75'
                                                    'nifti/fmri.nii,76'
                                                    'nifti/fmri.nii,77'
                                                    'nifti/fmri.nii,78'
                                                    'nifti/fmri.nii,79'
                                                    'nifti/fmri.nii,80'
                                                    'nifti/fmri.nii,81'
                                                    'nifti/fmri.nii,82'
                                                    'nifti/fmri.nii,83'
                                                    'nifti/fmri.nii,84'
                                                    'nifti/fmri.nii,85'
                                                    'nifti/fmri.nii,86'
                                                    'nifti/fmri.nii,87'
                                                    'nifti/fmri.nii,88'
                                                    'nifti/fmri.nii,89'
                                                    'nifti/fmri.nii,90'
                                                    'nifti/fmri.nii,91'
                                                    'nifti/fmri.nii,92'
                                                    'nifti/fmri.nii,93'
                                                    'nifti/fmri.nii,94'
                                                    'nifti/fmri.nii,95'
                                                    'nifti/fmri.nii,96'
                                                    'nifti/fmri.nii,97'
                                                    'nifti/fmri.nii,98'
                                                    'nifti/fmri.nii,99'
                                                    'nifti/fmri.nii,100'
                                                    'nifti/fmri.nii,101'
                                                    'nifti/fmri.nii,102'
                                                    'nifti/fmri.nii,103'
                                                    'nifti/fmri.nii,104'
                                                    'nifti/fmri.nii,105'
                                                    'nifti/fmri.nii,106'
                                                    'nifti/fmri.nii,107'
                                                    'nifti/fmri.nii,108'
                                                    'nifti/fmri.nii,109'
                                                    'nifti/fmri.nii,110'
                                                    'nifti/fmri.nii,111'
                                                    'nifti/fmri.nii,112'
                                                    'nifti/fmri.nii,113'
                                                    'nifti/fmri.nii,114'
                                                    'nifti/fmri.nii,115'
                                                    'nifti/fmri.nii,116'
                                                    'nifti/fmri.nii,117'
                                                    'nifti/fmri.nii,118'
                                                    'nifti/fmri.nii,119'
                                                    'nifti/fmri.nii,120'
                                                    'nifti/fmri.nii,121'
                                                    'nifti/fmri.nii,122'
                                                    'nifti/fmri.nii,123'
                                                    'nifti/fmri.nii,124'
                                                    'nifti/fmri.nii,125'
                                                    'nifti/fmri.nii,126'
                                                    'nifti/fmri.nii,127'
                                                    'nifti/fmri.nii,128'
                                                    'nifti/fmri.nii,129'
                                                    'nifti/fmri.nii,130'
                                                    'nifti/fmri.nii,131'
                                                    'nifti/fmri.nii,132'
                                                    'nifti/fmri.nii,133'
                                                    'nifti/fmri.nii,134'
                                                    'nifti/fmri.nii,135'
                                                    'nifti/fmri.nii,136'
                                                    'nifti/fmri.nii,137'
                                                    'nifti/fmri.nii,138'
                                                    'nifti/fmri.nii,139'
                                                    'nifti/fmri.nii,140'
                                                    'nifti/fmri.nii,141'
                                                    'nifti/fmri.nii,142'
                                                    'nifti/fmri.nii,143'
                                                    'nifti/fmri.nii,144'
                                                    'nifti/fmri.nii,145'
                                                    'nifti/fmri.nii,146'
                                                    'nifti/fmri.nii,147'
                                                    'nifti/fmri.nii,148'
                                                    'nifti/fmri.nii,149'
                                                    'nifti/fmri.nii,150'
                                                    'nifti/fmri.nii,151'
                                                    'nifti/fmri.nii,152'
                                                    'nifti/fmri.nii,153'
                                                    'nifti/fmri.nii,154'
                                                    'nifti/fmri.nii,155'
                                                    'nifti/fmri.nii,156'
                                                    'nifti/fmri.nii,157'
                                                    'nifti/fmri.nii,158'
                                                    'nifti/fmri.nii,159'
                                                    'nifti/fmri.nii,160'
                                                    'nifti/fmri.nii,161'
                                                    'nifti/fmri.nii,162'
                                                    'nifti/fmri.nii,163'
                                                    'nifti/fmri.nii,164'
                                                    'nifti/fmri.nii,165'
                                                    'nifti/fmri.nii,166'
                                                    'nifti/fmri.nii,167'
                                                    'nifti/fmri.nii,168'
                                                    'nifti/fmri.nii,169'
                                                    'nifti/fmri.nii,170'
                                                    'nifti/fmri.nii,171'
                                                    'nifti/fmri.nii,172'
                                                    'nifti/fmri.nii,173'
                                                    'nifti/fmri.nii,174'
                                                    'nifti/fmri.nii,175'
                                                    'nifti/fmri.nii,176'
                                                    'nifti/fmri.nii,177'
                                                    'nifti/fmri.nii,178'
                                                    'nifti/fmri.nii,179'
                                                    'nifti/fmri.nii,180'
                                                    'nifti/fmri.nii,181'
                                                    'nifti/fmri.nii,182'
                                                    'nifti/fmri.nii,183'
                                                    'nifti/fmri.nii,184'
                                                    'nifti/fmri.nii,185'
                                                    'nifti/fmri.nii,186'
                                                    'nifti/fmri.nii,187'
                                                    'nifti/fmri.nii,188'
                                                    'nifti/fmri.nii,189'
                                                    'nifti/fmri.nii,190'
                                                    'nifti/fmri.nii,191'
                                                    'nifti/fmri.nii,192'
                                                    'nifti/fmri.nii,193'
                                                    'nifti/fmri.nii,194'
                                                    'nifti/fmri.nii,195'
                                                    'nifti/fmri.nii,196'
                                                    'nifti/fmri.nii,197'
                                                    'nifti/fmri.nii,198'
                                                    'nifti/fmri.nii,199'
                                                    'nifti/fmri.nii,200'
                                                    'nifti/fmri.nii,201'
                                                    'nifti/fmri.nii,202'
                                                    'nifti/fmri.nii,203'
                                                    'nifti/fmri.nii,204'
                                                    'nifti/fmri.nii,205'
                                                    'nifti/fmri.nii,206'
                                                    'nifti/fmri.nii,207'
                                                    'nifti/fmri.nii,208'
                                                    'nifti/fmri.nii,209'
                                                    'nifti/fmri.nii,210'
                                                    'nifti/fmri.nii,211'
                                                    'nifti/fmri.nii,212'
                                                    'nifti/fmri.nii,213'
                                                    'nifti/fmri.nii,214'
                                                    'nifti/fmri.nii,215'
                                                    'nifti/fmri.nii,216'
                                                    'nifti/fmri.nii,217'
                                                    'nifti/fmri.nii,218'
                                                    'nifti/fmri.nii,219'
                                                    'nifti/fmri.nii,220'
                                                    'nifti/fmri.nii,221'
                                                    'nifti/fmri.nii,222'
                                                    'nifti/fmri.nii,223'
                                                    'nifti/fmri.nii,224'
                                                    'nifti/fmri.nii,225'
                                                    'nifti/fmri.nii,226'
                                                    'nifti/fmri.nii,227'
                                                    'nifti/fmri.nii,228'
                                                    'nifti/fmri.nii,229'
                                                    'nifti/fmri.nii,230'
                                                    'nifti/fmri.nii,231'
                                                    'nifti/fmri.nii,232'
                                                    'nifti/fmri.nii,233'
                                                    'nifti/fmri.nii,234'
                                                    'nifti/fmri.nii,235'
                                                    'nifti/fmri.nii,236'
                                                    'nifti/fmri.nii,237'
                                                    'nifti/fmri.nii,238'
                                                    'nifti/fmri.nii,239'
                                                    'nifti/fmri.nii,240'
                                                    'nifti/fmri.nii,241'
                                                    'nifti/fmri.nii,242'
                                                    'nifti/fmri.nii,243'
                                                    'nifti/fmri.nii,244'
                                                    'nifti/fmri.nii,245'
                                                    'nifti/fmri.nii,246'
                                                    'nifti/fmri.nii,247'
                                                    'nifti/fmri.nii,248'
                                                    'nifti/fmri.nii,249'
                                                    'nifti/fmri.nii,250'
                                                    'nifti/fmri.nii,251'
                                                    'nifti/fmri.nii,252'
                                                    'nifti/fmri.nii,253'
                                                    'nifti/fmri.nii,254'
                                                    'nifti/fmri.nii,255'
                                                    'nifti/fmri.nii,256'
                                                    'nifti/fmri.nii,257'
                                                    'nifti/fmri.nii,258'
                                                    'nifti/fmri.nii,259'
                                                    'nifti/fmri.nii,260'
                                                    'nifti/fmri.nii,261'
                                                    'nifti/fmri.nii,262'
                                                    'nifti/fmri.nii,263'
                                                    'nifti/fmri.nii,264'
                                                    'nifti/fmri.nii,265'
                                                    'nifti/fmri.nii,266'
                                                    'nifti/fmri.nii,267'
                                                    'nifti/fmri.nii,268'
                                                    'nifti/fmri.nii,269'
                                                    'nifti/fmri.nii,270'
                                                    'nifti/fmri.nii,271'
                                                    'nifti/fmri.nii,272'
                                                    'nifti/fmri.nii,273'
                                                    'nifti/fmri.nii,274'
                                                    'nifti/fmri.nii,275'
                                                    'nifti/fmri.nii,276'
                                                    'nifti/fmri.nii,277'
                                                    'nifti/fmri.nii,278'
                                                    'nifti/fmri.nii,279'
                                                    'nifti/fmri.nii,280'
                                                    'nifti/fmri.nii,281'
                                                    'nifti/fmri.nii,282'
                                                    'nifti/fmri.nii,283'
                                                    'nifti/fmri.nii,284'
                                                    'nifti/fmri.nii,285'
                                                    'nifti/fmri.nii,286'
                                                    'nifti/fmri.nii,287'
                                                    'nifti/fmri.nii,288'
                                                    'nifti/fmri.nii,289'
                                                    'nifti/fmri.nii,290'
                                                    'nifti/fmri.nii,291'
                                                    'nifti/fmri.nii,292'
                                                    'nifti/fmri.nii,293'
                                                    'nifti/fmri.nii,294'
                                                    'nifti/fmri.nii,295'
                                                    'nifti/fmri.nii,296'
                                                    'nifti/fmri.nii,297'
                                                    'nifti/fmri.nii,298'
                                                    'nifti/fmri.nii,299'
                                                    'nifti/fmri.nii,300'
                                                    'nifti/fmri.nii,301'
                                                    'nifti/fmri.nii,302'
                                                    'nifti/fmri.nii,303'
                                                    'nifti/fmri.nii,304'
                                                    'nifti/fmri.nii,305'
                                                    'nifti/fmri.nii,306'
                                                    'nifti/fmri.nii,307'
                                                    'nifti/fmri.nii,308'
                                                    'nifti/fmri.nii,309'
                                                    'nifti/fmri.nii,310'
                                                    'nifti/fmri.nii,311'
                                                    'nifti/fmri.nii,312'
                                                    'nifti/fmri.nii,313'
                                                    'nifti/fmri.nii,314'
                                                    'nifti/fmri.nii,315'
                                                    'nifti/fmri.nii,316'
                                                    'nifti/fmri.nii,317'
                                                    'nifti/fmri.nii,318'
                                                    'nifti/fmri.nii,319'
                                                    'nifti/fmri.nii,320'
                                                    'nifti/fmri.nii,321'
                                                    'nifti/fmri.nii,322'
                                                    'nifti/fmri.nii,323'
                                                    'nifti/fmri.nii,324'
                                                    'nifti/fmri.nii,325'
                                                    'nifti/fmri.nii,326'
                                                    'nifti/fmri.nii,327'
                                                    'nifti/fmri.nii,328'
                                                    'nifti/fmri.nii,329'
                                                    'nifti/fmri.nii,330'
                                                    'nifti/fmri.nii,331'
                                                    'nifti/fmri.nii,332'
                                                    'nifti/fmri.nii,333'
                                                    'nifti/fmri.nii,334'
                                                    'nifti/fmri.nii,335'
                                                    'nifti/fmri.nii,336'
                                                    'nifti/fmri.nii,337'
                                                    'nifti/fmri.nii,338'
                                                    'nifti/fmri.nii,339'
                                                    'nifti/fmri.nii,340'
                                                    'nifti/fmri.nii,341'
                                                    'nifti/fmri.nii,342'
                                                    'nifti/fmri.nii,343'
                                                    'nifti/fmri.nii,344'
                                                    'nifti/fmri.nii,345'
                                                    'nifti/fmri.nii,346'
                                                    'nifti/fmri.nii,347'
                                                    'nifti/fmri.nii,348'
                                                    'nifti/fmri.nii,349'
                                                    'nifti/fmri.nii,350'
                                                    'nifti/fmri.nii,351'
                                                    'nifti/fmri.nii,352'
                                                    'nifti/fmri.nii,353'
                                                    'nifti/fmri.nii,354'
                                                    'nifti/fmri.nii,355'
                                                    'nifti/fmri.nii,356'
                                                    'nifti/fmri.nii,357'
                                                    'nifti/fmri.nii,358'
                                                    'nifti/fmri.nii,359'
                                                    'nifti/fmri.nii,360'
                                                    'nifti/fmri.nii,361'
                                                    'nifti/fmri.nii,362'
                                                    'nifti/fmri.nii,363'
                                                    'nifti/fmri.nii,364'
                                                    'nifti/fmri.nii,365'
                                                    'nifti/fmri.nii,366'
                                                    'nifti/fmri.nii,367'
                                                    'nifti/fmri.nii,368'
                                                    'nifti/fmri.nii,369'
                                                    'nifti/fmri.nii,370'
                                                    'nifti/fmri.nii,371'
                                                    'nifti/fmri.nii,372'
                                                    'nifti/fmri.nii,373'
                                                    'nifti/fmri.nii,374'
                                                    'nifti/fmri.nii,375'
                                                    'nifti/fmri.nii,376'
                                                    'nifti/fmri.nii,377'
                                                    'nifti/fmri.nii,378'
                                                    'nifti/fmri.nii,379'
                                                    'nifti/fmri.nii,380'
                                                    'nifti/fmri.nii,381'
                                                    'nifti/fmri.nii,382'
                                                    'nifti/fmri.nii,383'
                                                    'nifti/fmri.nii,384'
                                                    'nifti/fmri.nii,385'
                                                    'nifti/fmri.nii,386'
                                                    'nifti/fmri.nii,387'
                                                    'nifti/fmri.nii,388'
                                                    'nifti/fmri.nii,389'
                                                    'nifti/fmri.nii,390'
                                                    'nifti/fmri.nii,391'
                                                    'nifti/fmri.nii,392'
                                                    'nifti/fmri.nii,393'
                                                    'nifti/fmri.nii,394'
                                                    'nifti/fmri.nii,395'
                                                    'nifti/fmri.nii,396'
                                                    'nifti/fmri.nii,397'
                                                    'nifti/fmri.nii,398'
                                                    'nifti/fmri.nii,399'
                                                    'nifti/fmri.nii,400'
                                                    }
                                                    }';
%%
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.quality = 0.9;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.sep = 4;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.fwhm = 5;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.rtm = 1;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.interp = 4;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.wrap = [0 0 0];
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.weight = '';
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.which = [2 1];
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.interp = 4;
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.wrap = [0 0 0];
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.mask = 1;
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.prefix = 'r';
matlabbatch{2}.spm.spatial.coreg.estimate.ref(1) = cfg_dep('Realign: Estimate & Reslice: Mean Image', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','rmean'));
matlabbatch{2}.spm.spatial.coreg.estimate.source = {'nifti/struct.nii,1'};
matlabbatch{2}.spm.spatial.coreg.estimate.other = {''};
matlabbatch{2}.spm.spatial.coreg.estimate.eoptions.cost_fun = 'nmi';
matlabbatch{2}.spm.spatial.coreg.estimate.eoptions.sep = [4 2];
matlabbatch{2}.spm.spatial.coreg.estimate.eoptions.tol = [0.02 0.02 0.02 0.001 0.001 0.001 0.01 0.01 0.01 0.001 0.001 0.001];
matlabbatch{2}.spm.spatial.coreg.estimate.eoptions.fwhm = [7 7];
matlabbatch{3}.spm.spatial.preproc.channel.vols(1) = cfg_dep('Coregister: Estimate: Coregistered Images', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','cfiles'));
matlabbatch{3}.spm.spatial.preproc.channel.biasreg = 0.001;
matlabbatch{3}.spm.spatial.preproc.channel.biasfwhm = 60;
matlabbatch{3}.spm.spatial.preproc.channel.write = [1 1];
matlabbatch{3}.spm.spatial.preproc.tissue(1).tpm = {'C:\Users\kasperla\Documents\Code\spm12\tpm\TPM.nii,1'};
matlabbatch{3}.spm.spatial.preproc.tissue(1).ngaus = 1;
matlabbatch{3}.spm.spatial.preproc.tissue(1).native = [1 0];
matlabbatch{3}.spm.spatial.preproc.tissue(1).warped = [0 1];
matlabbatch{3}.spm.spatial.preproc.tissue(2).tpm = {'C:\Users\kasperla\Documents\Code\spm12\tpm\TPM.nii,2'};
matlabbatch{3}.spm.spatial.preproc.tissue(2).ngaus = 1;
matlabbatch{3}.spm.spatial.preproc.tissue(2).native = [1 0];
matlabbatch{3}.spm.spatial.preproc.tissue(2).warped = [0 1];
matlabbatch{3}.spm.spatial.preproc.tissue(3).tpm = {'C:\Users\kasperla\Documents\Code\spm12\tpm\TPM.nii,3'};
matlabbatch{3}.spm.spatial.preproc.tissue(3).ngaus = 2;
matlabbatch{3}.spm.spatial.preproc.tissue(3).native = [1 0];
matlabbatch{3}.spm.spatial.preproc.tissue(3).warped = [0 1];
matlabbatch{3}.spm.spatial.preproc.tissue(4).tpm = {'C:\Users\kasperla\Documents\Code\spm12\tpm\TPM.nii,4'};
matlabbatch{3}.spm.spatial.preproc.tissue(4).ngaus = 3;
matlabbatch{3}.spm.spatial.preproc.tissue(4).native = [1 0];
matlabbatch{3}.spm.spatial.preproc.tissue(4).warped = [0 0];
matlabbatch{3}.spm.spatial.preproc.tissue(5).tpm = {'C:\Users\kasperla\Documents\Code\spm12\tpm\TPM.nii,5'};
matlabbatch{3}.spm.spatial.preproc.tissue(5).ngaus = 4;
matlabbatch{3}.spm.spatial.preproc.tissue(5).native = [1 0];
matlabbatch{3}.spm.spatial.preproc.tissue(5).warped = [0 0];
matlabbatch{3}.spm.spatial.preproc.tissue(6).tpm = {'C:\Users\kasperla\Documents\Code\spm12\tpm\TPM.nii,6'};
matlabbatch{3}.spm.spatial.preproc.tissue(6).ngaus = 2;
matlabbatch{3}.spm.spatial.preproc.tissue(6).native = [0 0];
matlabbatch{3}.spm.spatial.preproc.tissue(6).warped = [0 0];
matlabbatch{3}.spm.spatial.preproc.warp.mrf = 1;
matlabbatch{3}.spm.spatial.preproc.warp.cleanup = 1;
matlabbatch{3}.spm.spatial.preproc.warp.reg = [0 0.001 0.5 0.05 0.2];
matlabbatch{3}.spm.spatial.preproc.warp.affreg = 'mni';
matlabbatch{3}.spm.spatial.preproc.warp.fwhm = 0;
matlabbatch{3}.spm.spatial.preproc.warp.samp = 3;
matlabbatch{3}.spm.spatial.preproc.warp.write = [0 1];
matlabbatch{3}.spm.spatial.preproc.warp.vox = NaN;
matlabbatch{3}.spm.spatial.preproc.warp.bb = [NaN NaN NaN
                                              NaN NaN NaN];
matlabbatch{4}.spm.spatial.normalise.write.subj.def(1) = cfg_dep('Segment: Forward Deformations', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','fordef', '()',{':'}));
matlabbatch{4}.spm.spatial.normalise.write.subj.resample(1) = cfg_dep('Segment: Bias Corrected (1)', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','channel', '()',{1}, '.','biascorr', '()',{':'}));
matlabbatch{4}.spm.spatial.normalise.write.woptions.bb = [-78 -112 -70
                                                          78 76 85];
matlabbatch{4}.spm.spatial.normalise.write.woptions.vox = [1 1 1];
matlabbatch{4}.spm.spatial.normalise.write.woptions.interp = 4;
matlabbatch{4}.spm.spatial.normalise.write.woptions.prefix = 'w';
matlabbatch{5}.spm.spatial.smooth.data(1) = cfg_dep('Realign: Estimate & Reslice: Resliced Images (Sess 1)', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','sess', '()',{1}, '.','rfiles'));
matlabbatch{5}.spm.spatial.smooth.fwhm = [3 3 3];
matlabbatch{5}.spm.spatial.smooth.dtype = 0;
matlabbatch{5}.spm.spatial.smooth.im = 0;
matlabbatch{5}.spm.spatial.smooth.prefix = 's';
